Vagrant.configure("2") do |config|
    # Define VM box to use
    config.vm.box = "trusty64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    # Configure the application server
    config.vm.define "app" do |app|
        app.vm.host_name = "app"
        app.vm.network :private_network, ip: "10.10.2.20", netmask: "255.255.255.0", adapter: 2

        # Add the root folder
        app.vm.synced_folder "../root" , "/var/www/"

        config.vm.provision :puppet do |puppet|
            puppet.manifests_path = "provision/manifests"
            puppet.module_path = "provision/modules"
        end
    end
end
